# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.20.0'

    - uses: actions/checkout@v3

    - name: Verify dependencies
      run: go mod verify
      env:
        GO111MODULE: auto

    - name: Install dependencies
      run: |
        go mod download all
        go mod tidy -compat=1.20
      env:
        GO111MODULE: auto

    - name: Test
      run: go test -v ./...
      env:
        GO111MODULE: auto